Feature/hongil
wecode-bootcamp-korea/10-ok-bujangnim-backend pull request #3
Opened 2020-07-28 05:34 UTC by hongalLee

메인페이지 api 작업(main)
리스트 api 작업(board)
상세페이지 api 작업(read)

2020-07-28 08:54 UTC, soheon-lee commented on board/models.py
>      updated_at = models.DateTimeField()
`=`기준으로 정렬해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/models.py
>      product = models.ForeignKey(Product,on_delete = models.CASCADE)
=기준으로 정렬해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/models.py
>      updated_at = models.DateTimeField()
`=`기준으로 정렬해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/models.py
>      updated_at = models.DateTimeField()
`=`기준으로 정렬해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/views.py
>  from django.shortcuts import render
사용하지 않는 코드 삭제해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/views.py
>  # Create your views here.
사용하지 않는 코드 삭제해주세요

2020-07-28 08:54 UTC, soheon-lee commented on board/views.py
> +from main.models import Catalog, Category
```suggestion
from main.models import (
    Catalog, 
    Category
)
```

2020-07-28 08:54 UTC, soheon-lee commented on board/views.py
> +        category_list = Category.objects.filter(catalog_id=catalog_id, is_activated='Y').values()
catalog_id를 받아오셨기 때문에 catalog 객체 가운데 유일한 하나를 지칭할 수 있다는 의미가 됩니다. 카탈로그 객체가 하나 정해지면, 카테고리는 이에 연결되어 있으므로 카테고리 객체에 접근하지 않고 역참조해서 카테고리 객체에 접근하실 수 있습니다.

2020-07-28 08:54 UTC, soheon-lee commented on board/views.py
> +                'image_url': product.image_set.all()[0].image_url,
쿼리셋에서 가장 첫 요소를 가져오는 메소드가 있습니다. 인덱싱보다 해당 메소드를 활용해보세요 :)

2020-07-28 08:54 UTC, soheon-lee commented on main/models.py
>      updated_at = models.DateTimeField()
`=`기준으로 정렬해주세요

2020-07-28 08:54 UTC, soheon-lee commented on main/views.py
>  from board.models import Product, Image
```suggestion
from board.models import (
    Product, 
    Image
)
```

2020-07-28 08:54 UTC, soheon-lee commented on read/views.py
> +        'scent': product.characteristic_set.all()[0].scent,
쿼리셋에서 가장 첫 요소를 가져오는 메소드가 있습니다. 인덱싱보다 해당 메소드를 활용해보세요 :)

2020-07-28 08:54 UTC, soheon-lee commented on read/views.py
> +    return JsonResponse({'result': 'SUCCESS', 'data': {'item': list(product_result)}}, status=200)
view 앱에 있는 함수를 board 앱에 클래스형으로 이동시켜주시길 바랍니다 :)

2020-07-29 06:40 UTC, evergreen-david requested changes

2020-07-29 06:40 UTC, evergreen-david commented on aesop_project/settings.py
> +
공백 삭제 부탁 드립니다.

2020-07-29 06:40 UTC, evergreen-david commented on aesop_project/urls.py
>      #path('admin/', admin.site.urls),
admin 삭제 부탁 드립니다.

2020-07-29 06:40 UTC, evergreen-david commented on board/views.py
> +        product_items = Category.objects.filter(id=category_id, is_activated='Y').prefetch_related(
쿼리 한번에 효율적으로 할 수 있는지 검토 부탁 드립니다.

2020-07-30 07:24 UTC, evergreen-david requested changes

2020-07-30 07:24 UTC, evergreen-david commented on board/views.py
> +            'category_set__product_set__image_set').filter(id=catalog_id, is_activated='Y')
```suggestion
            'category_set__product_set__image_set').filter(id=catalog_id, is_activated=True)
```

2020-07-30 07:24 UTC, evergreen-david commented on board/views.py
> +            'category_set__product_set__image_set').filter(id=catalog_id, is_activated='Y')
```suggestion
            'category_set__product_set__image_set').filter(id=catalog_id, is_activated=True)
```

2020-07-30 07:24 UTC, evergreen-david commented on board/models.py
> +    faceType     = models.ForeignKey(FaceType, on_delete = models.CASCADE)
```suggestion
    face_type     = models.ForeignKey(FaceType, on_delete = models.CASCADE)
```

2020-07-30 11:22 UTC, evergreen-david approved these changes

2020-07-30 11:22 UTC, merged